<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_27";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                // ================== CREDENTIALS ==================
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",

                // ================== CUSTOMERS ==================
                "INSERT INTO " + schema + ".CUSTOMER(ID, USR, PSW) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'guillermo', 'gpc')",
                "INSERT INTO " + schema + ".CUSTOMER(ID, USR, PSW) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'alvaro', 'apc')",

                // ================== CAPABILITIES ==================
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'chat-completion')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'code-generation')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'image-generation')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'translation')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'summarization')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'speech-recognition')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'text-to-speech')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'semantic-search')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'question-answering')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'data-analysis')",

                // ================== PROVIDERS ==================
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'OpenAi')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'Meta')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'Google')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'Anthropic')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'Cohere')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'HuggingFace')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'DeepMind')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'AI21')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'StabilityAI')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'EleutherAI')",

                // ================== LICENSES ==================
                "INSERT INTO " + schema + ".LICENSE VALUES (NEXT VALUE FOR LICENSE_GEN, 'Permissive Open Source Licenses')",
                "INSERT INTO " + schema + ".LICENSE VALUES (NEXT VALUE FOR LICENSE_GEN, 'Propietary')",
                "INSERT INTO " + schema + ".LICENSE VALUES (NEXT VALUE FOR LICENSE_GEN, 'Custom')",
                "INSERT INTO " + schema + ".LICENSE VALUES (NEXT VALUE FOR LICENSE_GEN, 'Academic')",
                "INSERT INTO " + schema + ".LICENSE VALUES (NEXT VALUE FOR LICENSE_GEN, 'GPL')",

                // ================== MODELS ==================
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, PRIV, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                    "VALUES (NEXT VALUE FOR MODEL_GEN, 'o3-pro', 'Advanced chat-completion and code generation model by OpenAI, optimized for multi-turn conversations and coding tasks.', 20000, 0.91, 0, {d '2024-05-01'}, {d '2025-07-01'}, '2025-06-10', 27, 1, 3)",
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, PRIV, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                    "VALUES (NEXT VALUE FOR MODEL_GEN, 'gemini', 'Google Gemini model, excels in language understanding, multi-domain generation, and multilingual tasks.', 20000, 0.91, 1, {d '2024-05-01'}, {d '2025-07-01'}, '2025-06-10', 27, 3, 3)",
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, PRIV, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                    "VALUES (NEXT VALUE FOR MODEL_GEN, 'claude', 'Claude model from Anthropic focusing on safety-aligned AI and advanced reasoning across multiple tasks.', 15000, 0.88, 0, {d '2024-06-15'}, {d '2025-07-10'}, '1.2', 22, 4, 2)",
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, PRIV, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                    "VALUES (NEXT VALUE FOR MODEL_GEN, 'cohere-x', 'Cohere X model designed for NLP, text analytics, summarization, and semantic search.', 10000, 0.85, 1, {d '2024-07-01'}, {d '2025-06-20'}, '3.0', 15, 5, 1)",
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, PRIV, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                    "VALUES (NEXT VALUE FOR MODEL_GEN, 'dalle', 'DALL·E image generation model, creates high-quality images from textual descriptions.', 5000, 0.92, 0, {d '2023-12-10'}, {d '2025-07-05'}, '2.1', 5, 1, 2)",
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, PRIV, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                    "VALUES (NEXT VALUE FOR MODEL_GEN, 'bard', 'Google Bard model for conversational AI, question answering, and multi-turn dialogue.', 18000, 0.90, 0, {d '2024-02-20'}, {d '2025-06-30'}, '1.0', 30, 3, 3)",
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, PRIV, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                    "VALUES (NEXT VALUE FOR MODEL_GEN, 'speechify', 'Text-to-speech and speech recognition model supporting multiple languages and accents.', 12000, 0.87, 1, {d '2024-03-10'}, {d '2025-07-01'}, '2.0', 20, 6, 1)",
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, PRIV, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                    "VALUES (NEXT VALUE FOR MODEL_GEN, 'semantic-pro', 'Advanced semantic search model capable of understanding context and retrieving precise information.', 8000, 0.89, 0, {d '2024-04-01'}, {d '2025-07-10'}, '1.5', 12, 7, 4)",

                // ================== MODEL_CAPACITY RELATIONS ==================
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (1, 1)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (1, 2)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (2, 1)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (2, 3)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (2, 4)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (3, 2)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (3, 5)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (3, 6)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (4, 2)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (4, 4)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (5, 3)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (5, 5)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (5, 1)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (5, 10)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (6, 1)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (6, 5)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (7, 2)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (7, 7)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (8, 8)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (8, 9)"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>

