<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_27";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'chat-completion')",
                "INSERT INTO " + schema + ".CAPABILITY VALUES (NEXT VALUE FOR CAP_GEN, 'code-generation')",
                
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'OpenAi')",
                "INSERT INTO " + schema + ".PROVIDER VALUES (NEXT VALUE FOR PROVIDER_GEN, 'Meta')",
                
                "INSERT INTO " + schema + ".LICENSE VALUES (NEXT VALUE FOR LICENSE_GEN, 'Permissive Open Source Licenses')",
                "INSERT INTO " + schema + ".LICENSE VALUES (NEXT VALUE FOR LICENSE_GEN, 'Propietary')",
                "INSERT INTO " + schema + ".LICENSE VALUES (NEXT VALUE FOR LICENSE_GEN, 'Custom')",
                
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                                            "VALUES (NEXT VALUE FOR MODEL_GEN, 'o3-pro', 'o3-pro model of OpenAI', 20000, " + 
                                                      " 0.91, {d '2024-05-01'}, {d '2025-07-01'},'2025-06-10', 27, 1, 3)",
                "INSERT INTO " + schema + ".MODEL(ID, NAME, DESCR, CL, QI, TRAIN_D, LAST_D, VERSION, N_LANG, PROVIDER_ID, LICENSE_ID) " +
                                            "VALUES (NEXT VALUE FOR MODEL_GEN, 'gemini', 'gemini of Google', 20000, " + 
                                                      " 0.91, {d '2024-05-01'}, {d '2025-07-01'},'2025-06-10', 27, 2, 3)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (1, 1)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (1, 2)",
                "INSERT INTO " + schema + ".MODEL_CAPACITY(MODEL_ID, CAP_ID) VALUES (2, 2)"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>

